### ISSUE TITLE
Improvement 1 : We don't know how to select which font 

### ISSUE THREAD

**Issue by Natgru06** [Natgru06/ASCIIArtGen_Pundogar-Nathan_TD1_CDOF3#2]
When we have to select a font we don't know which one to choose if we want another font than the default one

**Comment by Flozoui** [comment]
I'll do it !!
Make a list of different font

**Comment by Natgru06** [comment]
okay thx

**Comment by Natgru06** [comment]
Issue fixed improvement is good
